# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: math_functions.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "math_functions.InputNumbers" do
    optional :n1, :int32, 1
    optional :n2, :int32, 2
  end
  add_message "math_functions.ResultNumber" do
    optional :result, :int32, 1
  end
end

module MathFunctions
  InputNumbers = Google::Protobuf::DescriptorPool.generated_pool.lookup("math_functions.InputNumbers").msgclass
  ResultNumber = Google::Protobuf::DescriptorPool.generated_pool.lookup("math_functions.ResultNumber").msgclass
end
